---
title: "MP4"
author: Natalia Iannucci and Hana Hirano
output: 
  html_document:
    code_folding: hide
---
```{r message = FALSE, warning = FALSE}
library(tidyverse)
library(RMySQL)
library(DBI)
db <- dbConnect(MySQL(), 
                host = "scidb.smith.edu", 
                user = "mth292", 
                password = "RememberPi", 
                dbname = "citibike")
knitr::opts_chunk$set(connection = db, max.print = 20)
```


Will give the distances for the most popular start station (I sorted just that data in descedning order to find the right one) from greatest to least distance, and then shows the age, and all only for women
```{r}
women <- dbGetQuery(db, 
"SELECT gender, AVG(t.duration / 60) AS avg_duration_in_min, AVG(2019 - t.birth_year) AS avg_age, name
FROM trips AS t
LEFT JOIN station_months 
	ON station_months.station_id = t.start_station_id
WHERE gender = 2
	AND start_time LIKE '2017-01%'
GROUP BY name
HAVING avg_age < 100
ORDER BY avg_duration_in_min DESC"
)
```


this is the same thing for men so we could compare the two
```{r}
men <- dbGetQuery(db, 
"SELECT gender, AVG(t.duration / 60) AS avg_duration_in_min, AVG(2019 - t.birth_year) AS avg_age, name
FROM trips AS t
LEFT JOIN station_months 
	ON station_months.station_id = t.start_station_id
WHERE gender = 1
	AND start_time LIKE '2017-01%'
GROUP BY name
HAVING avg_age < 100
ORDER BY avg_duration_in_min DESC"
)
```


this shows the relationship between their age and duration of their ride
```{r}
duration_age <- dbGetQuery(db, 
"SELECT (t.duration / 60) AS duration_in_min, (2019 - t.birth_year) AS age
FROM trips AS t
WHERE t.birth_year > 1919
GROUP BY age
ORDER BY age"
)
```


